services:
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_TOKEN: ${API_TOKEN}
    env_file:
      - .env
    environment:
      - REACT_APP_API_TOKEN=${API_TOKEN}
    ports:
      - "3000:80"
    networks:
      - proxy
      - front
  
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://${PSQL_USER}:${PSQL_PASSWORD}@db:5432/${PSQL_DB}
    volumes:
      - uploads_data:/app/uploads    # Persistent storage for uploaded files
    networks:
      - front
      - back
  
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back

volumes:
  db_data:
  uploads_data:     # Define volume for uploads

networks:
  front:
  back:
  proxy:
    name: traefik
    external: true